core/urls.py
from django.urls import path     
from . import views
# from . import views_forms

# http://127.0.0.1:8000/core/
app_name = 'core'

urlpatterns = [
    path('', views.indexcore, name='index'),	   
]

login_reg_app/urls.py
from django.urls import path
# from . import views
from .views import LoginLocal, RegisterLocal, logout, workload, validador
# from login_reg_app import views

app_name = 'login_reg_app'

urlpatterns = [
    
    path('', LoginLocal.as_view(), name='login'),
    path('register/', RegisterLocal.as_view(), name='register'),
    path('logout/', logout, name='logout'),
    path('validador/', validador.as_view(), name='validador'),
    path('workload/', workload, name='workload')
    # path('', views.Login_Reg),
    # path('register', views.Register),
    # path('login', views.Login),
    # path('success', views.Success),
    # path('logout', views.Logout)
]

plantilla33/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('login_reg_app.urls')),
    path('dashboard/', include('plantilla33_app.urls')),
    path('core/', include('core.urls')),
    path('social-auth/',include('social_django.urls',namespace='social')),  #url asociada a la autenticacion de google
    path('admin/', admin.site.urls),
]

plantilla33_app/urls.py
from django.urls import path
from plantilla33_app import views
from .views import AddNewDev, Dashboard, EditDev

from django.conf import settings 
from django.conf.urls.static import static 


app_name='plantilla33_app'

urlpatterns = [
    path('', Dashboard.as_view(), name='dashboard'),
    path('wall/new', AddNewDev.as_view(), name='new_device'),
    path('wall/<int:id>/', views.ViewDev),
    path('wall/<int:id>/edit', EditDev.as_view(), name='edit_device'),
    path('wall/<int:id>/update', views.EditDev.as_view(), name='update_device'),
    path('wall/<int:id>/destroy', views.DeleteDev),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)   

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def indexcore(request):
    return HttpResponse("this is the equivalent of @core.route('/')!")

core/templates/core/foundation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %} {% endblock %}</title>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    {% block estilos %} 
    {% endblock %}

</head>

<body>
{% block contenido %}
{% include 'core/header.html' %}  
{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

<script>

    toastr.options = {
        "closeButton": true,
        "progressBar": true,
    }

    {% if messages %}
    {% for message in messages %}
        toastr.{{ message.tags }}('{{ message }}', 'MENSAJE!!');
    {% endfor %}
    {% endif %}

</script>

{% block scripts %} 
{% endblock %} 

</body>
</html>

core/templates/core/header.html
{% load static %}

<div class="navbar navbar-expand-lg  d-flex justify-content-around border-bottom shadow-sm bg-dark">
    
    <a href="{% url 'plantilla33_app:dashboard' %}" class="navbar-brand my-0 mr-md-autofont-weight-normal ">
        <img src="{% static '/images/smart.png' %}" alt="Logo smartagro" width="164" height="76">
    </a>

    
    <h1 class="navbar-brand">Smart Agro: <span class="text-primary">{% block titulo %} {% endblock %}</span></h1>
    
    <div class="d-flex">
        <span class="form-control me-2">Bienvenid@ {{request.session.usuario.nombre}} {{request.user.first_name}} </span>
        <a href="{% url 'login_reg_app:logout' %}" class="btn btn-secondary">Salir</a>
    </div>

</div>
{% comment %} first_name es el campo en la base de datos que se crea en django para las autenticaciones {% endcomment %}