core/urls.py
from django.urls import path     
from . import views
# from . import views_forms

# http://127.0.0.1:8000/core/
app_name = 'core'

urlpatterns = [
    path('', views.indexcore, name='index'),	   
]

login_reg_app/urls.py
from django.urls import path
# from . import views
from .views import LoginLocal, RegisterLocal, logout, workload, validador
# from login_reg_app import views

app_name = 'login_reg_app'

urlpatterns = [
    
    path('', LoginLocal.as_view(), name='login'),
    path('register/', RegisterLocal.as_view(), name='register'),
    path('logout/', logout, name='logout'),
    path('validador/', validador.as_view(), name='validador'),
    path('workload/', workload, name='workload')
    # path('', views.Login_Reg),
    # path('register', views.Register),
    # path('login', views.Login),
    # path('success', views.Success),
    # path('logout', views.Logout)
]

plantilla33/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('login_reg_app.urls')),
    path('dashboard/', include('plantilla33_app.urls')),
    path('core/', include('core.urls')),
    path('social-auth/',include('social_django.urls',namespace='social')),  #url asociada a la autenticacion de google
    path('admin/', admin.site.urls),
]

login_reg_app/models.py
from __future__ import unicode_literals
from django.db import models



class User(models.Model):
    nombre = models.CharField(max_length=45, unique=True, verbose_name="Nombre", default=None)
    username = models.CharField(max_length=45, unique=True, verbose_name="Username", default=None)
    email = models.CharField(max_length=200, unique=True, verbose_name="Email", default=None)
    password = models.CharField(max_length=72, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # objects = UserManager()

    def __repr__(self):
        return f"User ID: {self.id}| nombre: {self.nombre}| Last Name: {self.username}| Email: {self.email}| Password: {self.password} ||"

login_reg_app/forms.py
from django import forms
from login_reg_app.models import User
from login_reg_app.views import *

class RegisterForm(forms.ModelForm):
    
    class Meta:
        model = User    #Usuario es la clase creada en la BD
        fields = ['nombre', 'username', 'email', 'password']
        
        labels = {
            'nombre': 'Nombre:  ',
            'username': 'Username:  ',
            'email': 'Correo  ',  
            'password': 'Contraseña  ',
        }
        
        # verbose_name = ['nombre de usuario', 'username', 'email', 'password']
        
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}), 
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),  
        }

class LoginForm(forms.ModelForm):
    
    class Meta:
        model = User    #Usuario es la clase creada en la BD
        fields = ['username', 'password']
                
        labels = {
            'username': 'User/Correo:  ',
            'password': 'Contraseña  ',
        }    
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}), 
            'password': forms.PasswordInput(attrs={'class': 'form-control'}), 
        }
        
        
             
        
 

login_reg_app/views.py
from django.shortcuts import render, redirect, reverse
from login_reg_app.models import User
from django.db.models import Q
from django.contrib import messages
import bcrypt
from django.views import View
from login_reg_app.forms import LoginForm, RegisterForm
from django.urls import reverse
from login_reg_app.email import EmailThread

# Create your views here.

class LoginLocal(View):
    def get(self, request):
        
        if 'usuario' in request.session:
            messages.error(request, 'Ya estas logeado, para salir click en salir')
            return redirect ("/workload")
        
        contexto = {
            'formLogin': LoginForm(),
            }
        print(contexto)
        return render(request, 'login_reg_app/login.html', contexto)
    
    def post(self, request):
        print(request.POST)
        form = LoginForm(request.POST)
        
        if form.is_valid():
            
            user = User.objects.filter(Q(username=form.cleaned_data['username'])| Q(email=form.cleaned_data['username'])).first()
            if user:
                form_password = form.cleaned_data['password']
                if bcrypt.checkpw(form_password.encode(), user.password.encode()):
                # Si existe el usuario y si obtenemos True después de validar la contraseña, podemos poner la identificación del usuario en la sesión
                    print(f'*'*10,'estoy verificando')
                    messages.success(request, 'Bienvenido')
                    request.session['usuario'] = { 'nombre' : user.nombre, 'username' : user.username, 'email' : user.email, 'id' : user.id}
                    request.session['id'] = user.id
                    # iduser = request.session['usuario'] 
                    # idname=iduser['nombre']
                    return redirect(reverse('plantilla33_app:dashboard'))                    
                    # contexto = {}
                    # return render(request, 'login_reg_app/workload.html', contexto)

                else:
                    print(f'*'*10,'1. contraseña  email nombre incorrecto')
                    messages.error(request, 'Contraseña o username incorrecto')
            else: #si no existe el usuario
                messages.error(request, 'Contraseña o username incorrecto')
                print(f'*'*10,'2. contraseña  email nombre incorrecto')
                
            return redirect(reverse('login_reg_app:login'))
    
class RegisterLocal(View):
    def get(self, request):
        
        if 'usuario' in request.session:
            messages.error(request, 'Ya estas logeado, para salir click en salir')
            return redirect ("/workload") #esto se podria llevar a una clase para ahorrar codigo
        
        contexto = {
            'formRegister': RegisterForm(),
        }
        print(contexto)
        return render(request, 'login_reg_app/register.html', contexto)
    
    def post(self, request):
        print(request.POST)
        
        form = RegisterForm(request.POST) #cargar los datos al formulario
        # print(form)

        
        if form.is_valid():
            usuario=form.save(commit=False) #commit=false no se guarda en la Bds
            usuario.password =bcrypt.hashpw(usuario.password.encode(), bcrypt.gensalt()).decode()
            usuario.save()
            messages.success(request, 'usuario agregado correctamente')
            
            EmailThread("Correo de Prueba ASINCRONICA", 
                        'login_reg_app/correo.html', 
                        ['ingenieroteleco@gmail.com']
                        ).start()
            
            
            return redirect(reverse('login_reg_app:login'))
        else:            
            contexto = {
                'formRegister': RegisterForm,
            }
            print('*'*20,contexto)
            messages.error(request, 'con errores en los campos, solucionar')
            return render(request, 'login_reg_app/register.html', contexto)  #devolver el mismo form, para no cargar uno nuevo
        

def logout(request):
    if 'usuario' in request.session:
        del request.session['usuario']
        messages.info(request, "Para volver a entrar debes logearte nuevamente")
        return redirect(reverse('login_reg_app:login'))

def workload(request):
    if request.method == 'GET':
        context = {}
        return render(request, 'login_reg_app/workload.html', context)
    
class validador(View):  #se puede optimizar? reusando la clase, como hago para el return
    def get(self, request):
        
        # if 'usuario' in request.session:
        #     messages.error(request, 'Ya estas logeado, para salir click en salir')
        #     return redirect ("/workload")
        
        contexto = {
            'formLogin': LoginForm(),
            }
        print(contexto)
        return render(request, 'login_reg_app/validador.html', contexto)
    
# def Login_Reg(request):
#     return render(request, 'login_reg.html')

# def Register(request):
#     print(request.POST)
#     errors = User.objects.validate_register(request.POST)
#     if len(errors) > 0:
#         print("Errors",errors)
#         for key, value in errors.items():
#             messages.error(request, value)
#         return redirect('/')
#     else:
#         pwhash = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())
#         user = User.objects.create(first_name=request.POST['first_name'], last_name=request.POST['last_name'], email=request.POST['email'], password=pwhash.decode())
#         print("User: ", user)
#         request.session['id'] = user.id
#     return redirect('/dashboard')

# def Login(request):
#     errors = User.objects.validate_login(request.POST)
#     if len(errors) > 0:
#         for key, value in errors.items():
#             messages.error(request, value)
#         return redirect('/')
#     else:
#         user = User.objects.get(email=request.POST['email'])
#         request.session['id'] = user.id
#     return redirect('/dashboard')

# def Success(request):
#     user = User.objects.get(id=request.session['id'])
#     return render(request, 'login_reg_app/success.html', {'user':user})

# def Logout(request):
#     request.session.clear()
#     print("Logged Out")
#     return redirect('/')

login_reg_app/templates/login_reg_app/correo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
</head>
<body>
    <h1>Bienvenido a SMARTAGRO</h1>
    <p>Variable del CONTEXTO: {{usuario}}</p>
    <p>Desde la variable de SESION: {{session_user}}</p>
    <p>acceder al siguiente link para darse de alta en el sistema. Tienes 24 hrs para realizar la confirmación. <a href="http:127.0.0.1:8000/validador">Link en este enlace para validar</a><p>
</body>
</html>

login_reg_app/templates/login_reg_app/login.html
{% extends "core/foundation.html" %}
{% block titulo %} Login {% endblock %}
{% block contenido %}
{% include 'core/header.html' %} 

{% comment %} <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="description" content="A really cool site!">
    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script> {% endcomment %}
    {% comment %} {% load static %}
    <link rel="stylesheet" href="{% static 'login_reg_app/css/custom-bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'login_reg_app/css/style.css' %}">
    <script src="{% static 'login_reg_app/js/script.js' %}"></script>
</head> {% endcomment %}
<div class="container mt-5">
    <div class="row">
        <div class="col-4"> </div>
        <div class="col-5"> 
        <h3><i class="fa fa-sign-in" aria-hidden="true"></i> LOGIN </h3>
        </div>
        <div class="col-4"> </div>
        <div class="col-5 border border-light rounded-3 shadow p-3 mb-5 bg-body rounded">
            
            <form action="{% url 'login_reg_app:login' %}" method="post" >
                {% csrf_token %}
                {{ formLogin.non_field_errors }}   

                {% for field in formLogin %}
                <div class="mt-3 row">


                    <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field }}
                    </div>

                    {% if field.errors %}

                    <div class="alert alert-danger mt-2" role="alert">
                        {% for error in field.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>

                    {% endif %}

                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="mb-3 row">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-9">
                        <button class="mt-4 px-5 btn btn-primary rounded-pill offset-2 google" type="submit"> <i class="fa fa-plus-circle" aria-hidden="true"></i> Ingresar </button>
                    </div>
                </div>
            </form>
            <div class="mb-3 row">
                <div class="col-sm-3"></div>
                <div class="col-sm-9">
                <a class="btn btn-outline-primary rounded-pill" href="{% url 'login_reg_app:register'%}"> <i class="fa fa-user-plus" aria-hidden="true"></i> Crear una cuenta </a>
            </div>
            <div class="mb-3 row">
                <div class="col-sm-5"></div>
                <div class="col-sm-7">
                <p class="mt-4 fs-6"> o continúa con </p>
            </div>
            <div class="mb-3 row">
                <div class="col-sm-5"></div>
                <div class="col-sm-7">
                <a class="px-5 btn btn-outline-danger rounded-pill" href="{% url 'social:begin' 'google-oauth2' %}"> <i class="fa fa-google" aria-hidden="true"></i> Google </a>
                {% comment %} colocar la url asociada en el proyecto para realizar la coneccion {% endcomment %}
            </div>
            <div class="mt-3 row">
                <div class="col-sm-5"></div>
                <div class="col-sm-7">
                <button class="px-5 btn btn-outline-primary rounded-pill" type="submit" href="{% url 'social:begin' 'github' %}"> <i class="fa fa-facebook-official" aria-hidden="true"></i> Github </button>
            </div>
        
        

        </div> 
    </div>
</div>

{% endblock %}
                {% comment %} <div class="mb-3 row">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-9">
                        <button class="btn btn-primary offset-2 google" type="submit"> <i class="fa fa-plus-circle" aria-hidden="true"></i> REGISTRARSE </button>
                    </div>
                </div>
            </form>
        </div> 
        <div class="col-2"></div>
        <div class="col-5 align-self-center">
            
            <a class="btn btn-sm btn-danger me-1" href="{% url 'social:begin' 'google-oauth2' %}"> <i class="fa fa-google-plus" aria-hidden="true"></i> Sign in with Google </a>
            <a class="btn btn-sm btn-primary me-1" href="{% url 'social:begin' 'google-oauth2' %}"> <i class="fa fa-facebook-official" aria-hidden="true"></i> Sign in with Facebook </a>
        </div>
    </div>
</div> {% endcomment %}



{% comment %} <body>
    <div class="container">
        <!-- Registration and Login titles -->
        <div class="row mt-5">
            <div class="col justify-content-start">
                <h1 class="mb-5 text-center display-4"><strong>Registration</strong></h1>
            </div>
            <div class="col"></div>
            <div class="col text-center">
                <h1 class="mb-5 text-center display-4"><strong>Login</strong></h1>
            </div>
        </div>
        <!-- Registration sub-titles and input fields -->
        <div class="row">
            <div class="col justify-content-center">
                <form action="/register" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        {% if messages %}
                        <ul class="messages mb-4 error-box none">
                            {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label class="custom-title" for="first_name">First Name</label>
                        <input type="text" class="form-control ml-3" id="first_name" name="first_name">
                    </div>
                    <div class="form-group">
                        <label class="custom-title mt-2" for="last_name">Last Name</label>
                        <input type="text" class="form-control ml-3" id="last_name" name="last_name">
                    </div>
                    <div class="form-group">
                        <label class="custom-title mt-2" for="email">Email</label>
                        <input type="email" class="form-control ml-3" id="email" name="email">
                    </div>
                    <div class="form-group">
                        <label class="custom-title mt-2" for="password">Password</label>
                        <input type="password" class="form-control ml-3" id="password" name="password">
                    </div>
                    <div class="form-group">
                        <label class="custom-title mt-2" for="conf_password">Confirm Password</label>
                        <input type="password" class="form-control ml-3" id="conf_password" name="conf_password">
                    </div>
                    <div class="text-center">
                        <button type="submit" class="text-center btn btn-primary mt-2 pl-4 pr-4">Register</button>
                    </div>
                </form>
            </div>
            <div class="col"></div>
            <!-- Login sub-titles and input fields -->
            <div class="col">
                <form action="/login" method="POST">
                    {% if messages %}
                    <ul class="messages mb-4 error-box">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="custom-title" for="email">Email</label>
                        <input type="email" class="form-control ml-3" id="email" name="email">
                    </div>
                    <div class="form-group">
                        <label class="custom-title mt-2" for="password">Password</label>
                        <input type="password" class="form-control ml-3" id="password" name="password">
                    </div>
                    <div class="text-center">
                        <button type="submit" class="text-center btn btn-primary mt-2 pl-4 pr-4">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

</html> {% endcomment %}

login_reg_app/templates/login_reg_app/success.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="description" content="A really cool site!">
    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'login_reg_app/css/custom-bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'login_reg_app/css/style.css' %}">
    <script src="{% static 'login_reg_app/js/script.js' %}"></script>
</head>

<body>
    <nav class="navbar navbar-dark bg-dark">
        <img src="{% static 'login_reg_app/images/coding_dojo_logo.png' %}" />
        <h1 class="navbar-brand">Coding Dojo: <span class="text-primary">Success</span></h1>
        <form class="form-inline">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </nav>

    <div class="container">
        <div class="row justify-content-end mt-5">
            <form action="/logout" method="POST">
                <button type="submit" class="text-center btn btn-outline-primary mt-2 pl-4 pr-4">&#8249;&nbsp;Logout</button>
            </form>
        </div>
        <div class="row">
            <div class="col display-1">
                <h1>Success! Welcome, {{ user.first_name }} {{ user.last_name }}!</h1>
            </div>
        </div>
    </div>
</body>

</html>

login_reg_app/templates/login_reg_app/validador.html
{% extends "core/foundation.html" %}
{% block titulo %} Validador {% endblock %}
{% block contenido %}
{% include 'core/header.html' %} 

{% comment %} <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="description" content="A really cool site!">
    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script> {% endcomment %}
    {% comment %} {% load static %}
    <link rel="stylesheet" href="{% static 'login_reg_app/css/custom-bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'login_reg_app/css/style.css' %}">
    <script src="{% static 'login_reg_app/js/script.js' %}"></script>
</head> {% endcomment %}
<div class="container mt-5">
    <div class="row">
        <div class="col-4"> </div>
        <div class="col-5"> 
        <h3><i class="fa fa-sign-in" aria-hidden="true"></i> VALIDADOR </h3>
        </div>
        <div class="col-4"> </div>
        <div class="col-5 border border-light rounded-3 shadow p-3 mb-5 bg-body rounded">
            
            <form action="{% url 'login_reg_app:workload' %}" method="post" >
                {% csrf_token %}
                {{ formLogin.non_field_errors }}   

                {% for field in formLogin %}
                <div class="mt-3 row">


                    <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field }}
                    </div>

                    {% if field.errors %}

                    <div class="alert alert-danger mt-2" role="alert">
                        {% for error in field.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>

                    {% endif %}

                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="mb-3 row">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-9">
                        <button class="mt-4 px-5 btn btn-primary rounded-pill offset-2 google" type="submit"> <i class="fa fa-plus-circle" aria-hidden="true"></i> Ingresar </button>
                    </div>
                </div>
            </div> 
    </div>
</div>

{% endblock %}
                {% comment %} <div class="mb-3 row">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-9">
                        <button class="btn btn-primary offset-2 google" type="submit"> <i class="fa fa-plus-circle" aria-hidden="true"></i> REGISTRARSE </button>
                    </div>
                </div>
            </form>
        </div> 
        <div class="col-2"></div>
        <div class="col-5 align-self-center">
            
            <a class="btn btn-sm btn-danger me-1" href="{% url 'social:begin' 'google-oauth2' %}"> <i class="fa fa-google-plus" aria-hidden="true"></i> Sign in with Google </a>
            <a class="btn btn-sm btn-primary me-1" href="{% url 'social:begin' 'google-oauth2' %}"> <i class="fa fa-facebook-official" aria-hidden="true"></i> Sign in with Facebook </a>
        </div>
    </div>
</div> {% endcomment %}



{% comment %} <body>
    <div class="container">
        <!-- Registration and Login titles -->
        <div class="row mt-5">
            <div class="col justify-content-start">
                <h1 class="mb-5 text-center display-4"><strong>Registration</strong></h1>
            </div>
            <div class="col"></div>
            <div class="col text-center">
                <h1 class="mb-5 text-center display-4"><strong>Login</strong></h1>
            </div>
        </div>
        <!-- Registration sub-titles and input fields -->
        <div class="row">
            <div class="col justify-content-center">
                <form action="/register" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        {% if messages %}
                        <ul class="messages mb-4 error-box none">
                            {% for message in messages %}
                            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <label class="custom-title" for="first_name">First Name</label>
                        <input type="text" class="form-control ml-3" id="first_name" name="first_name">
                    </div>
                    <div class="form-group">
                        <label class="custom-title mt-2" for="last_name">Last Name</label>
                        <input type="text" class="form-control ml-3" id="last_name" name="last_name">
                    </div>
                    <div class="form-group">
                        <label class="custom-title mt-2" for="email">Email</label>
                        <input type="email" class="form-control ml-3" id="email" name="email">
                    </div>
                    <div class="form-group">
                        <label class="custom-title mt-2" for="password">Password</label>
                        <input type="password" class="form-control ml-3" id="password" name="password">
                    </div>
                    <div class="form-group">
                        <label class="custom-title mt-2" for="conf_password">Confirm Password</label>
                        <input type="password" class="form-control ml-3" id="conf_password" name="conf_password">
                    </div>
                    <div class="text-center">
                        <button type="submit" class="text-center btn btn-primary mt-2 pl-4 pr-4">Register</button>
                    </div>
                </form>
            </div>
            <div class="col"></div>
            <!-- Login sub-titles and input fields -->
            <div class="col">
                <form action="/login" method="POST">
                    {% if messages %}
                    <ul class="messages mb-4 error-box">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="custom-title" for="email">Email</label>
                        <input type="email" class="form-control ml-3" id="email" name="email">
                    </div>
                    <div class="form-group">
                        <label class="custom-title mt-2" for="password">Password</label>
                        <input type="password" class="form-control ml-3" id="password" name="password">
                    </div>
                    <div class="text-center">
                        <button type="submit" class="text-center btn btn-primary mt-2 pl-4 pr-4">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

</html> {% endcomment %}

login_reg_app/templates/login_reg_app/workload.html
{% extends "core/foundation.html" %}
{% block titulo %} Logeado {% endblock %}
{% block contenido %}
{% include 'core/header.html' %} 

<h1> Esto es una prueba, bienvenico </h1>
{% endblock %}